STORE_DIR = './store/'
CUSTOMER_DIR = STORE_DIR + 'customers/'
ARRIVAL_TIME_TEXT  = 'Arrival Time'
CAR_INDENTITY_TEXT = 'Car Identity'
FREQUENT_PARKING_NUMBER_TEXT = 'Frequent Parking Number'
BILL_DIR = STORE_DIR + 'bills/'